#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/lgtvctl
CONFIG=/etc/lgtvctl.toml

start_service() {
	[ -x "$PROG" ] || return 1
	[ -f "$CONFIG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" --config "$CONFIG" serve
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

reload_service() {
	stop
	start
}
